export const businessPage = {
  coverphotoid: null,
  logoid: null,
  username: "Mock username",
  companyname: "Mock company name",
  bio: `Lorem ipsum dolor sit amet, consectetuer adipiscing
        elit. Aenean commodo ligula eget dolor. Aenean massa.
        Cum sociis natoque penatibus et magnis dis parturient
        montes, nascetur ridiculus ...`,
  occupations: ["mock 1", "mock 2", "mock 3"],
  industries: ["Industries mock 1", "Industries mock 2", "Industries mock 3"],
  homebusiness: {
    contactdetails: {
      address: {
        addressLine1: " The cupboard under the Stairs",
        addressLine2: "4 Privet Drive, Little Whinging",
        country: "UK",
        county: "",
        postcode: "PL29 3SD",
        town: "Scotland",
      },
      phonenumber1: "+91 9075130623",
      phonenumber2: "+91 9075130623",
      email: "mock@email.com",
    },
    openingtimes: [
      {
        day: 0,
        starttime: "Tue Mar 23 2021 14:23:41 GMT+0530 (India Standard Time)",
        endtime: "Tue Mar 23 2021 14:23:41 GMT+0530 (India Standard Time)",
      },
      {
        day: 1,
        starttime: "Tue Mar 23 2021 14:23:41 GMT+0530 (India Standard Time)",
        endtime: "Tue Mar 23 2021 14:23:41 GMT+0530 (India Standard Time)",
      },
      {
        day: 2,
        starttime: "Tue Mar 23 2021 14:23:41 GMT+0530 (India Standard Time)",
        endtime: "Tue Mar 23 2021 14:23:41 GMT+0530 (India Standard Time)",
      },
    ],
  },
  mobile: {
    contactdetails: {
      address: {
        addressLine1: " The cupboard under the Stairs",
        addressLine2: "4 Privet Drive, Little Whinging",
        country: "UK",
        county: "",
        postcode: "PL29 3SD",
        town: "Scotland",
      },
      phonenumber1: "+91 9075130623",
      phonenumber2: "+91 9075130623",
      email: "mock@email.com",
    },
    openingtimes: [
      {
        day: 0,
        starttime: "Tue Mar 23 2021 14:23:41 GMT+0530 (India Standard Time)",
        endtime: "Tue Mar 23 2021 14:23:41 GMT+0530 (India Standard Time)",
      },
      {
        day: 1,
        starttime: "Tue Mar 23 2021 14:23:41 GMT+0530 (India Standard Time)",
        endtime: "Tue Mar 23 2021 14:23:41 GMT+0530 (India Standard Time)",
      },
      {
        day: 2,
        starttime: "Tue Mar 23 2021 14:23:41 GMT+0530 (India Standard Time)",
        endtime: "Tue Mar 23 2021 14:23:41 GMT+0530 (India Standard Time)",
      },
    ],
  },
  shop: {
    contactdetails: {
      address: {
        addressLine1: " The cupboard under the Stairs",
        addressLine2: "4 Privet Drive, Little Whinging",
        country: "UK",
        county: "",
        postcode: "PL29 3SD",
        town: "Scotland",
      },
      phonenumber1: "+91 9075130623",
      phonenumber2: "+91 9075130623",
      email: "mock@email.com",
    },
    openingtimes: [
      {
        day: 0,
        starttime: "Tue Mar 23 2021 14:23:41 GMT+0530 (India Standard Time)",
        endtime: "Tue Mar 23 2021 14:23:41 GMT+0530 (India Standard Time)",
      },
      {
        day: 1,
        starttime: "Tue Mar 23 2021 14:23:41 GMT+0530 (India Standard Time)",
        endtime: "Tue Mar 23 2021 14:23:41 GMT+0530 (India Standard Time)",
      },
      {
        day: 2,
        starttime: "Tue Mar 23 2021 14:23:41 GMT+0530 (India Standard Time)",
        endtime: "Tue Mar 23 2021 14:23:41 GMT+0530 (India Standard Time)",
      },
    ],
  },

  services: {
    tabOne: {
      heading: "Mock Service Heading 1",
      subservices: [
        {
          appoinmentvia: ["", "mobile", ""],
          appoinmentviastring: "",
          haslinebreak: false,
          id: "",
          name: "asfd",
          price: 4325,
          sequenceKey: 0,
          tabItemId: null,
          timereqquired: 1611741790000,
        },
        {
          appoinmentvia: ["", "mobile", ""],
          appoinmentviastring: "",
          haslinebreak: false,
          id: "",
          name: "asfd",
          price: 4325,
          sequenceKey: 0,
          tabItemId: null,
          timereqquired: 1611741790000,
        },
        {
          appoinmentvia: ["", "mobile", ""],
          appoinmentviastring: "",
          haslinebreak: false,
          id: "",
          name: "asfd",
          price: 4325,
          sequenceKey: 0,
          tabItemId: null,
          timereqquired: 1611741790000,
        },
      ],
    },
    tabTwo: {
      heading: "Mock Service Heading 2",
      subservices: [
        {
          appoinmentvia: ["", "mobile", ""],
          appoinmentviastring: "",
          haslinebreak: false,
          id: "",
          name: "asfd",
          price: 4325,
          sequenceKey: 0,
          tabItemId: null,
          timereqquired: 1611741790000,
        },
        {
          appoinmentvia: ["", "mobile", ""],
          appoinmentviastring: "",
          haslinebreak: false,
          id: "",
          name: "asfd",
          price: 4325,
          sequenceKey: 0,
          tabItemId: null,
          timereqquired: 1611741790000,
        },
        {
          appoinmentvia: ["", "mobile", ""],
          appoinmentviastring: "",
          haslinebreak: false,
          id: "",
          name: "asfd",
          price: 4325,
          sequenceKey: 0,
          tabItemId: null,
          timereqquired: 1611741790000,
        },
      ],
    },
    tabThree: {
      heading: "Mock Service Heading 1",
      subservices: [
        {
          appoinmentvia: ["", "mobile", ""],
          appoinmentviastring: "",
          haslinebreak: false,
          id: "",
          name: "asfd",
          price: 4325,
          sequenceKey: 0,
          tabItemId: null,
          timereqquired: 1611741790000,
        },
        {
          appoinmentvia: ["", "mobile", ""],
          appoinmentviastring: "",
          haslinebreak: false,
          id: "",
          name: "asfd",
          price: 4325,
          sequenceKey: 0,
          tabItemId: null,
          timereqquired: 1611741790000,
        },
        {
          appoinmentvia: ["", "mobile", ""],
          appoinmentviastring: "",
          haslinebreak: false,
          id: "",
          name: "asfd",
          price: 4325,
          sequenceKey: 0,
          tabItemId: null,
          timereqquired: 1611741790000,
        },
      ],
    },
  },
};
