export const SpecialOfferData = [
  {
    id: 1,
    discount: "20% OFF",
    category: "Lorems in Sept 2020",
    handle: "@Handle",
    distance: "1.3 miles",
    companyName: "Comapany name character limit..",
    types: ["Home Business", "Mobile", "Shop"],
    ratings: 4.5,
    totalRatings: 678,
    likes: "2.376K",
    industries: ["Industry 1", "Industry 2", "Occupation 1", "Occupation 2"],
    image1: "/images/fav_iamge.png",
  },
  {
    id: 2,
    discount: "20% OFF",
    category: "Lorems in Sept 2020",
    handle: "@Handle",
    distance: "1.3 miles",
    companyName: "Comapany name character limit..",
    types: ["Home Business", "Mobile", "Shop"],
    ratings: 4.5,
    totalRatings: 678,
    likes: "2.376K",
    industries: ["Industry 1", "Industry 2", "Occupation 1", "Occupation 2"],
    image1: "/images/fav_iamge.png",
  },
  {
    id: 3,
    discount: "20% OFF",
    category: "Lorems in Sept 2020",
    handle: "@Handle",
    distance: "1.3 miles",
    companyName: "Comapany name character limit..",
    types: ["Home Business", "Mobile", "Shop"],
    ratings: 4.5,
    totalRatings: 678,
    likes: "2.376K",
    industries: ["Industry 1", "Industry 2", "Occupation 1", "Occupation 2"],
    image1: "/images/fav_iamge.png",
  },
  {
    id: 4,
    discount: "20% OFF",
    category: "Lorems in Sept 2020",
    handle: "@Handle",
    distance: "1.3 miles",
    companyName: "Comapany name character limit..",
    types: ["Home Business", "Mobile", "Shop"],
    ratings: 4.5,
    totalRatings: 678,
    likes: "2.376K",
    industries: ["Industry 1", "Industry 2", "Occupation 1", "Occupation 2"],
    image1: "/images/fav_iamge.png",
  },
  {
    id: 5,
    discount: "20% OFF",
    category: "Lorems in Sept 2020",
    handle: "@Handle",
    distance: "1.3 miles",
    companyName: "Comapany name character limit..",
    types: ["Home Business", "Mobile", "Shop"],
    ratings: 4.5,
    totalRatings: 678,
    likes: "2.376K",
    industries: ["Industry 1", "Industry 2", "Occupation 1", "Occupation 2"],
    image1: "/images/fav_iamge.png",
  },
  {
    id: 6,
    discount: "20% OFF",
    category: "Lorems in Sept 2020",
    handle: "@Handle",
    distance: "1.3 miles",
    companyName: "Comapany name character limit..",
    types: ["Home Business", "Mobile", "Shop"],
    ratings: 4.5,
    totalRatings: 678,
    likes: "2.376K",
    industries: ["Industry 1", "Industry 2", "Occupation 1", "Occupation 2"],
    image1: "/images/fav_iamge.png",
  },
];

export const industryFilterdata = [
  {
    id: 1,
    name: "Industry 1",
  },
  {
    id: 2,
    name: "Industry 2",
  },
  {
    id: 3,
    name: "Industry 3",
  },
];
